CREATE TABLE `deliverable` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` varchar(40) NOT NULL,
	`DESCRIPTION` TEXT,
	`DUE_DATE` DATE,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `requirement` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` varchar(40) NOT NULL,
	`SOURCE` TEXT NOT NULL,
	`LOCATION` TEXT NOT NULL,
	`REFERENCE` TEXT NOT NULL,
	`DELIVERABLE` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `task` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` varchar(40) NOT NULL,
	`DESCRIPTION` TEXT,
	`RESOURCE` INT,
	`EXPECTED_DURATION` TIME,
	`ACTUAL_DURATION` TIME,
	`EXPECTED_EFFORT` TIME,
	`ACTUAL_EFFORT` TIME,
	`EXPECTED_START` DATE,
	`EXPECTED_END` DATE,
	`ACTUAL_START` DATE,
	`ACTUAL_END` DATE,
	`PERCENT_COMPLETED` INT,
	`EFFORT_COMPLETED` TIME,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `resource` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` varchar(40) NOT NULL,
	`TITLE` varchar(40) NOT NULL,
	`SKILLS` TEXT,
	`AVAILABILITY` TEXT,
	`PAY_RATE` varchar(40) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `action_item` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` varchar(40) NOT NULL,
	`DESCRIPTION` TEXT,
	`PRIORITY` INT NOT NULL DEFAULT '5',
	`SEVERITY` INT NOT NULL DEFAULT '5',
	`DATE_RAISED` DATE,
	`DATE_ASSIGNED` DATE,
	`RESOURCE` INT,
	`EXPECTED_DATE` DATE,
	`ACTUAL_DATE` DATE,
	`STATUS` varchar(10) NOT NULL DEFAULT 'Open',
	`STATUS_DESCRIPTION` TEXT,
	`ASSOCIATED_ISSUE` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `issue` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` varchar(40) NOT NULL,
	`DESCRIPTION` TEXT,
	`SEVERITY` INT NOT NULL DEFAULT '5',
	`DATE_RAISED` DATE,
	`DATE_ASSIGNED` DATE,
	`RESOURCE` INT,
	`EXPECTED_DATE` DATE,
	`ACTUAL_DATE` DATE,
	`STATUS` varchar(10) NOT NULL DEFAULT 'Open',
	`STATUS_DESCRIPTION` TEXT,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `task_task` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`PREDECESSOR` INT NOT NULL,
	`SUCCESSOR` INT NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `requirement` ADD CONSTRAINT `requirement_fk0` FOREIGN KEY (`DELIVERABLE`) REFERENCES `deliverable`(`ID`);

ALTER TABLE `task` ADD CONSTRAINT `task_fk0` FOREIGN KEY (`RESOURCE`) REFERENCES `resource`(`ID`);

ALTER TABLE `action_item` ADD CONSTRAINT `action_item_fk0` FOREIGN KEY (`RESOURCE`) REFERENCES `resource`(`ID`);

ALTER TABLE `action_item` ADD CONSTRAINT `action_item_fk1` FOREIGN KEY (`ASSOCIATED_ISSUE`) REFERENCES `issue`(`ID`);

ALTER TABLE `issue` ADD CONSTRAINT `issue_fk0` FOREIGN KEY (`RESOURCE`) REFERENCES `resource`(`ID`);

ALTER TABLE `task_task` ADD CONSTRAINT `task_task_fk0` FOREIGN KEY (`PREDECESSOR`) REFERENCES `task`(`ID`);

ALTER TABLE `task_task` ADD CONSTRAINT `task_task_fk1` FOREIGN KEY (`SUCCESSOR`) REFERENCES `task`(`ID`);
